// <auto-generated />
namespace MigrationConflicts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dev2_addReaders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dev2_addReaders));
        
        string IMigrationMetadata.Id
        {
            get { return "201704130856177_dev2_addReaders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
